// src/a2a/event_translator.cpp — Build A2A streaming frames from
// orchestrator events.

#include "a2a/event_translator.h"

#include "json.h"

#include <utility>

namespace index_ai::a2a {

namespace {

// Generate a stable suffixed id for an artifact so the streaming client
// can identify deltas belonging to the same artifact.  We don't need
// cryptographic uniqueness here — within a single task the counter is
// monotonic and the prefix carries the task id.
std::string make_artifact_id(const std::string& task_id,
                              const std::string& kind, int seq) {
    return task_id + "-" + kind + "-" + std::to_string(seq);
}

} // namespace

A2aStreamWriter::A2aStreamWriter(EventSink sink,
                                  std::shared_ptr<JsonValue> rpc_id,
                                  std::string task_id,
                                  std::string context_id,
                                  std::string agent_id)
    : sink_(std::move(sink)),
      rpc_id_(std::move(rpc_id)),
      task_id_(std::move(task_id)),
      context_id_(std::move(context_id)),
      agent_id_(std::move(agent_id)) {
    text_artifact_id_ = make_artifact_id(task_id_, "text", 0);
}

void A2aStreamWriter::write_jsonrpc_result(std::shared_ptr<JsonValue> result) {
    RpcResponse r;
    r.id     = rpc_id_;
    r.result = std::move(result);
    sink_("message", to_json(r));
}

void A2aStreamWriter::emit_status(TaskState state, bool final,
                                   std::optional<Message> msg) {
    TaskStatusUpdateEvent e;
    e.task_id    = task_id_;
    e.context_id = context_id_;
    e.status.state    = state;
    e.status.message  = std::move(msg);
    e.final           = final;
    write_jsonrpc_result(to_json(e));
}

void A2aStreamWriter::emit_text_chunk(const std::string& delta, bool last_chunk) {
    if (delta.empty() && !last_chunk) return;

    bool first = !text_artifact_open_.exchange(true);

    TaskArtifactUpdateEvent e;
    e.task_id    = task_id_;
    e.context_id = context_id_;
    e.artifact.artifact_id = text_artifact_id_;
    if (first) {
        // Hint to the client that this artifact is the agent's
        // primary streaming response.  Optional but useful for
        // multi-artifact UIs that decide which one to render large.
        e.artifact.name        = "response";
        e.artifact.description = "agent's streaming text response";
    }
    Part p;
    p.kind = "text";
    p.text = delta;
    e.artifact.parts.push_back(std::move(p));

    // First chunk: append=false establishes the artifact.  Subsequent
    // chunks: append=true so the client concatenates onto the existing
    // artifact id rather than replacing it.
    e.append     = !first;
    e.last_chunk = last_chunk;
    write_jsonrpc_result(to_json(e));
}

void A2aStreamWriter::emit_tool_call(const std::string& tool_name, bool ok) {
    const int seq = tool_call_counter_.fetch_add(1);
    TaskArtifactUpdateEvent e;
    e.task_id    = task_id_;
    e.context_id = context_id_;
    e.artifact.artifact_id = make_artifact_id(task_id_, "tool", seq);
    e.artifact.name        = "tool_call";

    Part p;
    p.kind = "data";
    auto data = jobj();
    auto& m = data->as_object_mut();
    m["tool"] = jstr(tool_name);
    m["ok"]   = jbool(ok);
    p.data = data;

    auto md = jobj();
    md->as_object_mut()["x-arbiter.tool_call"] = jbool(true);
    p.metadata = md;

    e.artifact.parts.push_back(std::move(p));
    write_jsonrpc_result(to_json(e));
}

void A2aStreamWriter::emit_file(const std::string& path,
                                 const std::string& content,
                                 const std::string& mime_type) {
    const int seq = file_counter_.fetch_add(1);
    TaskArtifactUpdateEvent e;
    e.task_id    = task_id_;
    e.context_id = context_id_;
    e.artifact.artifact_id = make_artifact_id(task_id_, "file", seq);
    e.artifact.name        = path;
    e.artifact.description = "file generated by /write";

    Part p;
    p.kind = "file";
    // Inline as text bytes for now — A2A's file-with-bytes part is a
    // base64 string, so we'd need a base64 encoder for proper transit
    // of binary content.  arbiter's /write today emits utf-8 source
    // files almost exclusively; treat the content as text and ship it
    // verbatim until a binary use case shows up.  Spec readers know
    // mediaType="text/plain" means the bytes are the literal characters.
    p.file_bytes     = content;
    p.file_name      = path;
    p.file_mime_type = mime_type;
    e.artifact.parts.push_back(std::move(p));

    write_jsonrpc_result(to_json(e));
}

void A2aStreamWriter::emit_sub_agent(const std::string& sub_agent_id,
                                      int depth,
                                      const std::string& content) {
    const int seq = sub_agent_counter_.fetch_add(1);
    TaskArtifactUpdateEvent e;
    e.task_id    = task_id_;
    e.context_id = context_id_;
    e.artifact.artifact_id = make_artifact_id(task_id_, "sub", seq);
    e.artifact.name        = "sub_agent_response";
    e.artifact.description = sub_agent_id + " (depth " + std::to_string(depth) + ")";

    Part p;
    p.kind = "data";
    auto data = jobj();
    auto& m = data->as_object_mut();
    m["agent"]   = jstr(sub_agent_id);
    m["depth"]   = jnum(static_cast<double>(depth));
    m["content"] = jstr(content);
    p.data = data;

    auto md = jobj();
    md->as_object_mut()["x-arbiter.sub_agent_response"] = jbool(true);
    p.metadata = md;

    e.artifact.parts.push_back(std::move(p));
    write_jsonrpc_result(to_json(e));
}

void A2aStreamWriter::emit_metadata(const std::string& kind,
                                     std::shared_ptr<JsonValue> payload) {
    const int seq = metadata_counter_.fetch_add(1);
    TaskArtifactUpdateEvent e;
    e.task_id    = task_id_;
    e.context_id = context_id_;
    e.artifact.artifact_id = make_artifact_id(task_id_, "meta", seq);
    e.artifact.name        = kind;

    Part p;
    p.kind = "data";
    p.data = payload ? payload : jobj();

    auto md = jobj();
    md->as_object_mut()["x-arbiter." + kind] = jbool(true);
    p.metadata = md;

    e.artifact.parts.push_back(std::move(p));
    write_jsonrpc_result(to_json(e));
}

} // namespace index_ai::a2a
